# Docker compose for multi-org-ca-1
#DEV_MODE_DEV
version: '2'

networks:
  dfarm:

services:
  

  # Dfarmadmin peer1
  dfarmadmin-peer1.couchdb:
    container_name: dfarmadmin-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - dfarm

  dfarmadmin-peer1.dfarmadmin.com:
    container_name: dfarmadmin-peer1.dfarmadmin.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=dfarmadmin-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - dfarmadmin-peer1.couchdb

  # Dfarmretail peer1
  dfarmretail-peer1.couchdb:
    container_name: dfarmretail-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - dfarm

  dfarmretail-peer1.dfarmretail.com:
    container_name: dfarmretail-peer1.dfarmretail.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=dfarmretail-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - dfarmretail-peer1.couchdb
    