# Docker compose for multi-org-ca-1
#DEV_MODE_DEV
version: '2'

networks:
  dfarm:

services:
  

  # Dfarmadmin peer1
  dfarmadmin-peer1.dfarmadmin.com:
    container_name: dfarmadmin-peer1.dfarmadmin.com
    
    command: peer node start --peer-chaincodedev=true
    

  # Dfarmretail peer1
  dfarmretail-peer1.dfarmretail.com:
    container_name: dfarmretail-peer1.dfarmretail.com
    
    command: peer node start --peer-chaincodedev=true
    